"""Add fundamental_scores and trading_signals tables

Revision ID: d2497ea4a377
Revises: d0a4d9bae1f4
Create Date: 2025-11-13 00:40:10.834107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2497ea4a377'
down_revision: Union[str, None] = 'd0a4d9bae1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('f_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_scores_date'), 'fundamental_scores', ['date'], unique=False)
    op.create_index(op.f('ix_fundamental_scores_id'), 'fundamental_scores', ['id'], unique=False)
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('fundamental_score_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('signal_strength', sa.String(length=20), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fundamental_score_id'], ['fundamental_scores.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_signals_date'), 'trading_signals', ['date'], unique=False)
    op.create_index(op.f('ix_trading_signals_id'), 'trading_signals', ['id'], unique=False)
    op.create_index(op.f('ix_trading_signals_signal_type'), 'trading_signals', ['signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_signals_signal_type'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_date'), table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index(op.f('ix_fundamental_scores_id'), table_name='fundamental_scores')
    op.drop_index(op.f('ix_fundamental_scores_date'), table_name='fundamental_scores')
    op.drop_table('fundamental_scores')
    # ### end Alembic commands ###
